### ISSUE TITLE
Expose async API

### ISSUE THREAD

**Issue by ranma42** [unosquare/libfprint-cs#2]
libfprint comes with a very useful [async API](http://cgit.freedesktop.org/libfprint/libfprint/tree/libfprint/fprint.h#n319), which is currently not provided in libfprint-cs. Are there any plans to support it?
Would a PR to add it be acceptable?

**Comment by mariodivece** [comment]
I did notice the Async API was available but I originally write this wrapper to play around with a couple of sensors on a Raspberry Pi so I didn't think it was necessary. If you want to help out with that part by sending a Pull Request, that'd be great!

**Comment by mtugnoli** [comment]
I've tried to run, but this error occour : 
in this point :  
_var result = Interop.fp_init();_

this error occour :

"Unable to load DLL 'libfprint.so': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"}

**Comment by olalekan-agbaje** [comment]
I am getting the same error.

**Comment by gmbeas** [comment]
any ideas for error?
alguna idea por aquel error?

**Comment by ranma42** [comment]
The error is unrelated to this issue.

The most likely explanation for the error is that the libfprint library is not installed on your system. If you compiled and installed the libfprint library from source, check if it is in the correct path. Otherwise, check if the libfprint or libfprint0 (depending on your distribution) package is installed.
