### ISSUE TITLE
Unable to load DLL 'libfprint.so'

### ISSUE THREAD

**Issue by olalekan-agbaje** [unosquare/libfprint-cs#3]
Hi There,

I am currently trying out your codes and I am getting the error - Unable to load DLL 'libfprint.so': The specified module could not be found.

This is coming from the file 'FingerprintDeviceManager.cs' line 85. Is there anything I am doing wrong?

Any ideas on working round this? I am using C# on windows 8 by the way.

Thanks.

**Comment by ranma42** [comment]
@kafcom do you have the libfprint library?

You mentioned that you are on Windows... does libfprint work on windows?
Did you build & test it with a simple C application before trying this .NET wrapper?

**Comment by olalekan-agbaje** [comment]
Hello there,

Thanks for reaching out. I have downloaded and tried to install libfprint
for windows without success.

I use a windows 8.1 64bit system. Could you assist with getting ahead with
this problem?

**Comment by ranma42** [comment]
I am afraid you will encounter several issues as libfprint primarily targets Linux systems, but first of all I would check if the dependencies (libusb, glib, lib crypto) build and work correctly in your environment.

The [libfprint mailing list](https://www.freedesktop.org/wiki/Software/fprint/Mailing_list/) is probably the best place to look/ask for this information.

**Comment by olalekan-agbaje** [comment]
Ok, Thanks.

On Thu, Jul 14, 2016 at 1:42 PM, ranma42 notifications@github.com wrote:

> I am afraid you will encounter several issues as libfprint primarily
> targets Linux systems, but first of all I would check if the dependencies
> (libusb, glib, lib crypto) build and work correctly in your environment.
> 
> The libfprint mailing list
> https://www.freedesktop.org/wiki/Software/fprint/Mailing_list/ is
> probably the best place to look/ask for this information.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/unosquare/libfprint-cs/issues/3#issuecomment-232654454,
> or mute the thread
> https://github.com/notifications/unsubscribe/AA_D-CwqUAtgXMH6hmaxmjtyxxlh_ZPoks5qVi7FgaJpZM4IuLOJ
> .

## 

Regards,
Agbaje Olalekan
Nigeria - +2348037217418

**Comment by UlyssesAlves** [comment]
@olalekan-agbaje Have you been able to solve this in Windows?

**Comment by mariodivece** [comment]
I don't think you can build libfprint on Windows... Maybe try running Mono using Windows Subsystem for Linux? It's a long shot though...
https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux
https://msdn.microsoft.com/en-us/commandline/wsl/about

**Comment by UlyssesAlves** [comment]
I actually don't need to build libfprint on Windows. What I'm trying to do is rather to run a C# project on Visual Studio, and this project uses libfprint. This is the project: https://github.com/unosquare/libfprint-cs.

The code is pretty simple, but I get an error in execution time. The error is a System.DllNotFoundException which says that the "libfprint.so" was not found on my environment. Could the project work if I somehow find this file on the internet and save it in my root project?

**Comment by UlyssesAlves** [comment]
@mariodivece Sorry. Now I see I referenced the same project of this repository. Do you think then that it could be possible to get the binaries of this project to run on Windows? Maybe building the same *.so linux file as a *.dll windows libray. Maybe then we could use this project both on linux and windows. I'm just wondering, though. I've never seen a scenario like this before.

**Comment by aprf10** [comment]
@UlyssesAlves  did you resolve the problem, I have the same with that github project.

**Comment by UlyssesAlves** [comment]
@aprf10 Yes, I found a solution but with a different project than libfprint. Take a look at this repository: https://github.com/JcBernack/WinBioNET (specially the [ApiInformation.txt](https://github.com/JcBernack/WinBioNET/blob/master/ApiInformation.txt))

It's not being updated very much, but after trying plenty of other options I finally got Lenovo Preferred Pro USB Fingerprint Keyboard working on windows with that WinBioNET project.

**Comment by mariodivece** [comment]
Gentelemen, this is a LINUX project. I repeat, LINUX project.
