### ISSUE TITLE
FingerprintGallery add file .pgm

### ISSUE THREAD

**Issue by gmbeas** [unosquare/libfprint-cs#4]
Hi, how add to gallery file .pgm ??

Thanks =)

**Comment by gmbeas** [comment]
u.u

**Comment by gmbeas** [comment]
Alo??

**Comment by mariodivece** [comment]
This library is a wrapper to interact with fingerprint readers. I don't think you can simply add pgm files to the libfprint library. Use this library to scan fingerprints and then use something like SourceAFIS to create and identify fingerprints.

**Comment by gmbeas** [comment]
nice, thanks =)
