### ISSUE TITLE
Library crashes

### ISSUE THREAD

**Issue by WrongBit** [unosquare/libfprint-cs#8]
I try to use this wrapper on RaspberryPI (Raspbian buster). .NET Core 3.0; My code:

    var FPManager = FingerprintDeviceManager.Instance;
    FPManager.Initialize();
    var fpReaders = FPManager.DiscoverDevices();

At the last line program crashes with "Segmentation fault". Any idea?
In which environment this wrapper was successfully tested?
Thanks!

**Comment by geoperez** [comment]
This library was intended to be used with MONO.

**Comment by WrongBit** [comment]
@geoperez : Unfortunately yes. :) But current situation shows that Mono become "player #2" after .NET Core. Will you be so kind to test your library for Core? At least spot place where problem is. As every wrapper, it uses a lot of pointer conversions, maybe problem is there? Funny, but everything can be resolved just by using one more Attribute!
I wish I could help, but just investigation HOW library works can take for me a whole month.
Thanks!

**Comment by geoperez** [comment]
Hi @WrongBit 
I just updated the source code library to .NET Standard 2.0 and the sample to .NET Core App 3.0.

I don't have a device to test, so please give it a try.

Thanks

**Comment by WrongBit** [comment]
Geovanni, definitely will do! Thank you!!
