### ISSUE TITLE
How to compile and execute

### ISSUE THREAD

**Issue by GonzoAS** [unosquare/libfprint-cs#9]
Hi, I already downloaded the repo. I opened the solution in Visual Studio but when i want compile Unosquare.Labs.LibFprint.Tests to generate a .exe but cant find it

**Comment by GonzoAS** [comment]
I´m new in C#, I just want to see how it works, I already have my digitalPersona 4500 and intalled driver.

**Comment by GonzoAS** [comment]
nevermind, you have no solutions for windows right?

err: unable to load dll 'libfprint.so'

**Comment by geoperez** [comment]
Yeah, this library is for [libfprint](https://fprint.freedesktop.org/) and it's only supported by Linux and other *nixes.
